name: onyx
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_toggle_tab: ^1.3.0
  http: ^1.0.0
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  fluttertoast: ^8.2.1
  lottie: ^2.3.2
  flutter_secure_storage:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/